name: Scheduled Python Job

on:
  schedule:
    - cron: '0 21 * * *'  # 每分钟触发一次
  #手动触发
  #workflow_dispatch:

jobs:
  run_python_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 指定Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          #pip install -r requirements.txt  # 如果有依赖的话，在requirements.txt中列出

      - name: Run Python script
        run: python ./update_json.py  # 替换成您的Python脚本名称

      - name: Commit
        run: |
          git config --global user.email 905805357@qq.com
          git config --global user.name autoSubmissionRobot
          git add ./assets/citation_data.json
          git commit -m"action:`date`"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
